export type ProductType = {
  id?: number,
  name: String,
  type: string,
  brand: String,
  description: string,
  battery: string,
  cpu: string,
  operatingSystem: string,
  ram: string,
  screenReslution: string,
  screenSize: string,
  storage: string,
  thumbnail: string,
  image: string,
  weight: string,
  price: number,
  salePrice: number,
  quantity: number
}
